export const ADD_INGR: 'ADD_INGR' = 'ADD_INGR'
export const ADD_BUN: 'ADD_BUN' = 'ADD_BUN'

export const MOVE_INGR: 'MOVE_INGR' = 'MOVE_INGR'
export const REMOVE_INGR: 'REMOVE_INGR' = 'REMOVE_INGR'
export const HOVER_INGR: 'HOVER_INGR' = 'HOVER_INGR'

export const POST_ORDER_REQUEST: 'POST_ORDER_REQUEST' = 'POST_ORDER_REQUEST'
export const POST_ORDER_SUCCESS: 'POST_ORDER_SUCCESS' = 'POST_ORDER_SUCCESS'
export const POST_ORDER_FAILED: 'POST_ORDER_FAILED' = 'POST_ORDER_FAILED'