export const POST_EMAIL_REQUEST: 'POST_EMAIL_REQUEST' = 'POST_EMAIL_REQUEST'
export const POST_EMAIL_SUCCESS: 'POST_EMAIL_SUCCESS' = 'POST_EMAIL_SUCCESS'
export const POST_EMAIL_FAILED: 'POST_EMAIL_FAILED' = 'POST_EMAIL_FAILED'

export const POST_NEWPASSWORD_REQUEST: 'POST_NEWPASSWORD_REQUEST' = 'POST_NEWPASSWORD_REQUEST'
export const POST_NEWPASSWORD_SUCCESS: 'POST_NEWPASSWORD_SUCCESS' = 'POST_NEWPASSWORD_SUCCESS'
export const POST_NEWPASSWORD_FAILED: 'POST_NEWPASSWORD_FAILED' = 'POST_NEWPASSWORD_FAILED'