export const GET_PROFILE_REQUEST: 'GET_PROFILE_REQUEST' = 'GET_PROFILE_REQUEST'
export const GET_PROFILE_SUCCESS: 'GET_PROFILE_SUCCESS' = 'GET_PROFILE_SUCCESS'
export const GET_PROFILE_FAILED: 'GET_PROFILE_FAILED' = 'GET_PROFILE_FAILED'

export const PATCH_PROFILE_REQUEST: 'PATCH_PROFILE_REQUEST' = 'PATCH_PROFILE_REQUEST'
export const PATCH_PROFILE_SUCCESS: 'PATCH_PROFILE_SUCCESS' = 'PATCH_PROFILE_SUCCESS'
export const PATCH_PROFILE_FAILED: 'PATCH_PROFILE_FAILED' = 'PATCH_PROFILE_FAILED'